import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StarsCanvas from '@/components/StarCanvas'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { Analytics } from "@vercel/analytics/react"
import { getMyInfo } from "@/libs/action";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Suresh || Portfolio 2.0",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data: any = await getMyInfo();
  const info: infoProps = data.documents[0]

  return (
    <html lang="en">
      <body className=' bg-[#0d0d0d] text-white'>
        <StarsCanvas />
        <Navbar info={info} />
        {children}
        <Toaster />
        <Footer info={info}/>
        <Analytics />
      </body>
    </html>
  );
}
