import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StarsCanvas from '@/components/StarCanvas'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Suresh || Portfolio 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=' bg-[#0d0d0d] text-white'>
        <StarsCanvas />
        <Navbar/>
        {children}
        <Toaster/>
        <Footer/>
      </body>
    </html>
  );
}
